/**
 * 世界所有国家和地区数据 (250+个)
 * 包含193个联合国成员国 + 重要地区和领土
 * 热门国家优先排序，其余按英文名称字母顺序排序，包含大洲信息
 */
(function(global) {
    'use strict';

    global.COUNTRIES_DATA = [
        // 热门国家分组 - 优先显示
        { code: 'US', name: '美国', nameEn: 'United States', flag: '🇺🇸', continent: 'North America' },
        { code: 'GB', name: '英国', nameEn: 'United Kingdom', flag: '🇬🇧', continent: 'Europe' },
        { code: 'IN', name: '印度', nameEn: 'India', flag: '🇮🇳', continent: 'Asia' },
        { code: 'CA', name: '加拿大', nameEn: 'Canada', flag: '🇨🇦', continent: 'North America' },
        { code: 'DE', name: '德国', nameEn: 'Germany', flag: '🇩🇪', continent: 'Europe' },
        { code: 'FR', name: '法国', nameEn: 'France', flag: '🇫🇷', continent: 'Europe' },
        { code: 'IT', name: '意大利', nameEn: 'Italy', flag: '🇮🇹', continent: 'Europe' },
        { code: 'ES', name: '西班牙', nameEn: 'Spain', flag: '🇪🇸', continent: 'Europe' },
        { code: 'BR', name: '巴西', nameEn: 'Brazil', flag: '🇧🇷', continent: 'South America' },
        { code: 'JP', name: '日本', nameEn: 'Japan', flag: '🇯🇵', continent: 'Asia' },

        // 其他国家 - 按字母顺序排列
        { code: 'AF', name: '阿富汗', nameEn: 'Afghanistan', flag: '🇦🇫', continent: 'Asia' },
        { code: 'AL', name: '阿尔巴尼亚', nameEn: 'Albania', flag: '🇦🇱', continent: 'Europe' },
        { code: 'DZ', name: '阿尔及利亚', nameEn: 'Algeria', flag: '🇩🇿', continent: 'Africa' },
        { code: 'AS', name: '美属萨摩亚', nameEn: 'American Samoa', flag: '🇦🇸', continent: 'Oceania' },
        { code: 'AD', name: '安道尔', nameEn: 'Andorra', flag: '🇦🇩', continent: 'Europe' },
        { code: 'AO', name: '安哥拉', nameEn: 'Angola', flag: '🇦🇴', continent: 'Africa' },
        { code: 'AG', name: '安提瓜和巴布达', nameEn: 'Antigua and Barbuda', flag: '🇦🇬', continent: 'North America' },
        { code: 'AR', name: '阿根廷', nameEn: 'Argentina', flag: '🇦🇷', continent: 'South America' },
        { code: 'AM', name: '亚美尼亚', nameEn: 'Armenia', flag: '🇦🇲', continent: 'Asia' },
        { code: 'AU', name: '澳大利亚', nameEn: 'Australia', flag: '🇦🇺', continent: 'Oceania' },
        { code: 'AT', name: '奥地利', nameEn: 'Austria', flag: '🇦🇹', continent: 'Europe' },
        { code: 'AZ', name: '阿塞拜疆', nameEn: 'Azerbaijan', flag: '🇦🇿', continent: 'Asia' },
        { code: 'BS', name: '巴哈马', nameEn: 'Bahamas', flag: '🇧🇸', continent: 'North America' },
        { code: 'BH', name: '巴林', nameEn: 'Bahrain', flag: '🇧🇭', continent: 'Asia' },
        { code: 'BD', name: '孟加拉国', nameEn: 'Bangladesh', flag: '🇧🇩', continent: 'Asia' },
        { code: 'BB', name: '巴巴多斯', nameEn: 'Barbados', flag: '🇧🇧', continent: 'North America' },
        { code: 'BY', name: '白俄罗斯', nameEn: 'Belarus', flag: '🇧🇾', continent: 'Europe' },
        { code: 'BE', name: '比利时', nameEn: 'Belgium', flag: '🇧🇪', continent: 'Europe' },
        { code: 'BZ', name: '伯利兹', nameEn: 'Belize', flag: '🇧🇿', continent: 'North America' },
        { code: 'BJ', name: '贝宁', nameEn: 'Benin', flag: '🇧🇯', continent: 'Africa' },
        { code: 'BM', name: '百慕大', nameEn: 'Bermuda', flag: '🇧🇲', continent: 'North America' },
        { code: 'BT', name: '不丹', nameEn: 'Bhutan', flag: '🇧🇹', continent: 'Asia' },
        { code: 'BO', name: '玻利维亚', nameEn: 'Bolivia', flag: '🇧🇴', continent: 'South America' },
        { code: 'BA', name: '波黑', nameEn: 'Bosnia and Herzegovina', flag: '🇧🇦', continent: 'Europe' },
        { code: 'BW', name: '博茨瓦纳', nameEn: 'Botswana', flag: '🇧🇼', continent: 'Africa' },
        { code: 'VG', name: '英属维尔京群岛', nameEn: 'British Virgin Islands', flag: '🇻🇬', continent: 'North America' },
        { code: 'BN', name: '文莱', nameEn: 'Brunei', flag: '🇧🇳', continent: 'Asia' },
        { code: 'BG', name: '保加利亚', nameEn: 'Bulgaria', flag: '🇧🇬', continent: 'Europe' },
        { code: 'BF', name: '布基纳法索', nameEn: 'Burkina Faso', flag: '🇧🇫', continent: 'Africa' },
        { code: 'BI', name: '布隆迪', nameEn: 'Burundi', flag: '🇧🇮', continent: 'Africa' },
        { code: 'KH', name: '柬埔寨', nameEn: 'Cambodia', flag: '🇰🇭', continent: 'Asia' },
        { code: 'CM', name: '喀麦隆', nameEn: 'Cameroon', flag: '🇨🇲', continent: 'Africa' },
        { code: 'CV', name: '佛得角', nameEn: 'Cape Verde', flag: '🇨🇻', continent: 'Africa' },
        { code: 'KY', name: '开曼群岛', nameEn: 'Cayman Islands', flag: '🇰🇾', continent: 'North America' },
        { code: 'CF', name: '中非共和国', nameEn: 'Central African Republic', flag: '🇨🇫', continent: 'Africa' },
        { code: 'TD', name: '乍得', nameEn: 'Chad', flag: '🇹🇩', continent: 'Africa' },
        { code: 'CL', name: '智利', nameEn: 'Chile', flag: '🇨🇱', continent: 'South America' },
        { code: 'CN', name: '中国', nameEn: 'China', flag: '🇨🇳', continent: 'Asia' },
        { code: 'CO', name: '哥伦比亚', nameEn: 'Colombia', flag: '🇨🇴', continent: 'South America' },
        { code: 'KM', name: '科摩罗', nameEn: 'Comoros', flag: '🇰🇲', continent: 'Africa' },
        { code: 'CK', name: '库克群岛', nameEn: 'Cook Islands', flag: '🇨🇰', continent: 'Oceania' },
        { code: 'CR', name: '哥斯达黎加', nameEn: 'Costa Rica', flag: '🇨🇷', continent: 'North America' },
        { code: 'CI', name: '科特迪瓦', nameEn: 'Côte d\'Ivoire', flag: '🇨🇮', continent: 'Africa' },
        { code: 'HR', name: '克罗地亚', nameEn: 'Croatia', flag: '🇭🇷', continent: 'Europe' },
        { code: 'CU', name: '古巴', nameEn: 'Cuba', flag: '🇨🇺', continent: 'North America' },
        { code: 'CY', name: '塞浦路斯', nameEn: 'Cyprus', flag: '🇨🇾', continent: 'Asia' },
        { code: 'CZ', name: '捷克', nameEn: 'Czech Republic', flag: '🇨🇿', continent: 'Europe' },
        { code: 'CD', name: '刚果(金)', nameEn: 'Democratic Republic of the Congo', flag: '🇨🇩', continent: 'Africa' },
        { code: 'DK', name: '丹麦', nameEn: 'Denmark', flag: '🇩🇰', continent: 'Europe' },
        { code: 'DJ', name: '吉布提', nameEn: 'Djibouti', flag: '🇩🇯', continent: 'Africa' },
        { code: 'DM', name: '多米尼克', nameEn: 'Dominica', flag: '🇩🇲', continent: 'North America' },
        { code: 'DO', name: '多米尼加', nameEn: 'Dominican Republic', flag: '🇩🇴', continent: 'North America' },
        { code: 'EC', name: '厄瓜多尔', nameEn: 'Ecuador', flag: '🇪🇨', continent: 'South America' },
        { code: 'EG', name: '埃及', nameEn: 'Egypt', flag: '🇪🇬', continent: 'Africa' },
        { code: 'SV', name: '萨尔瓦多', nameEn: 'El Salvador', flag: '🇸🇻', continent: 'North America' },
        { code: 'GQ', name: '赤道几内亚', nameEn: 'Equatorial Guinea', flag: '🇬🇶', continent: 'Africa' },
        { code: 'ER', name: '厄立特里亚', nameEn: 'Eritrea', flag: '🇪🇷', continent: 'Africa' },
        { code: 'EE', name: '爱沙尼亚', nameEn: 'Estonia', flag: '🇪🇪', continent: 'Europe' },
        { code: 'SZ', name: '斯威士兰', nameEn: 'Eswatini', flag: '🇸🇿', continent: 'Africa' },
        { code: 'ET', name: '埃塞俄比亚', nameEn: 'Ethiopia', flag: '🇪🇹', continent: 'Africa' },
        { code: 'FJ', name: '斐济', nameEn: 'Fiji', flag: '🇫🇯', continent: 'Oceania' },
        { code: 'FI', name: '芬兰', nameEn: 'Finland', flag: '🇫🇮', continent: 'Europe' },
        { code: 'GA', name: '加蓬', nameEn: 'Gabon', flag: '🇬🇦', continent: 'Africa' },
        { code: 'GM', name: '冈比亚', nameEn: 'Gambia', flag: '🇬🇲', continent: 'Africa' },
        { code: 'GE', name: '格鲁吉亚', nameEn: 'Georgia', flag: '🇬🇪', continent: 'Asia' },
        { code: 'GH', name: '加纳', nameEn: 'Ghana', flag: '🇬🇭', continent: 'Africa' },
        { code: 'GR', name: '希腊', nameEn: 'Greece', flag: '🇬🇷', continent: 'Europe' },
        { code: 'GD', name: '格林纳达', nameEn: 'Grenada', flag: '🇬🇩', continent: 'North America' },
        { code: 'GT', name: '危地马拉', nameEn: 'Guatemala', flag: '🇬🇹', continent: 'North America' },
        { code: 'GN', name: '几内亚', nameEn: 'Guinea', flag: '🇬🇳', continent: 'Africa' },
        { code: 'GW', name: '几内亚比绍', nameEn: 'Guinea-Bissau', flag: '🇬🇼', continent: 'Africa' },
        { code: 'GY', name: '圭亚那', nameEn: 'Guyana', flag: '🇬🇾', continent: 'South America' },
        { code: 'HT', name: '海地', nameEn: 'Haiti', flag: '🇭🇹', continent: 'North America' },
        { code: 'HN', name: '洪都拉斯', nameEn: 'Honduras', flag: '🇭🇳', continent: 'North America' },
        { code: 'HU', name: '匈牙利', nameEn: 'Hungary', flag: '🇭🇺', continent: 'Europe' },
        { code: 'IS', name: '冰岛', nameEn: 'Iceland', flag: '🇮🇸', continent: 'Europe' },
        { code: 'ID', name: '印度尼西亚', nameEn: 'Indonesia', flag: '🇮🇩', continent: 'Asia' },
        { code: 'IR', name: '伊朗', nameEn: 'Iran', flag: '🇮🇷', continent: 'Asia' },
        { code: 'IQ', name: '伊拉克', nameEn: 'Iraq', flag: '🇮🇶', continent: 'Asia' },
        { code: 'IE', name: '爱尔兰', nameEn: 'Ireland', flag: '🇮🇪', continent: 'Europe' },
        { code: 'IL', name: '以色列', nameEn: 'Israel', flag: '🇮🇱', continent: 'Asia' },
        { code: 'JM', name: '牙买加', nameEn: 'Jamaica', flag: '🇯🇲', continent: 'North America' },
        { code: 'JO', name: '约旦', nameEn: 'Jordan', flag: '🇯🇴', continent: 'Asia' },
        { code: 'KZ', name: '哈萨克斯坦', nameEn: 'Kazakhstan', flag: '🇰🇿', continent: 'Asia' },
        { code: 'KE', name: '肯尼亚', nameEn: 'Kenya', flag: '🇰🇪', continent: 'Africa' },
        { code: 'KI', name: '基里巴斯', nameEn: 'Kiribati', flag: '🇰🇮', continent: 'Oceania' },
        { code: 'KP', name: '朝鲜', nameEn: 'Korea, North', flag: '🇰🇵', continent: 'Asia' },
        { code: 'KR', name: '韩国', nameEn: 'Korea, South', flag: '🇰🇷', continent: 'Asia' },
        { code: 'KW', name: '科威特', nameEn: 'Kuwait', flag: '🇰🇼', continent: 'Asia' },
        { code: 'KG', name: '吉尔吉斯斯坦', nameEn: 'Kyrgyzstan', flag: '🇰🇬', continent: 'Asia' },
        { code: 'LA', name: '老挝', nameEn: 'Laos', flag: '🇱🇦', continent: 'Asia' },
        { code: 'LV', name: '拉脱维亚', nameEn: 'Latvia', flag: '🇱🇻', continent: 'Europe' },
        { code: 'LB', name: '黎巴嫩', nameEn: 'Lebanon', flag: '🇱🇧', continent: 'Asia' },
        { code: 'LS', name: '莱索托', nameEn: 'Lesotho', flag: '🇱🇸', continent: 'Africa' },
        { code: 'LR', name: '利比里亚', nameEn: 'Liberia', flag: '🇱🇷', continent: 'Africa' },
        { code: 'LY', name: '利比亚', nameEn: 'Libya', flag: '🇱🇾', continent: 'Africa' },
        { code: 'LI', name: '列支敦士登', nameEn: 'Liechtenstein', flag: '🇱🇮', continent: 'Europe' },
        { code: 'LT', name: '立陶宛', nameEn: 'Lithuania', flag: '🇱🇹', continent: 'Europe' },
        { code: 'LU', name: '卢森堡', nameEn: 'Luxembourg', flag: '🇱🇺', continent: 'Europe' },
        { code: 'MK', name: '北马其顿', nameEn: 'Macedonia', flag: '🇲🇰', continent: 'Europe' },
        { code: 'MG', name: '马达加斯加', nameEn: 'Madagascar', flag: '🇲🇬', continent: 'Africa' },
        { code: 'MW', name: '马拉维', nameEn: 'Malawi', flag: '🇲🇼', continent: 'Africa' },
        { code: 'MY', name: '马来西亚', nameEn: 'Malaysia', flag: '🇲🇾', continent: 'Asia' },
        { code: 'MV', name: '马尔代夫', nameEn: 'Maldives', flag: '🇲🇻', continent: 'Asia' },
        { code: 'ML', name: '马里', nameEn: 'Mali', flag: '🇲🇱', continent: 'Africa' },
        { code: 'MT', name: '马耳他', nameEn: 'Malta', flag: '🇲🇹', continent: 'Europe' },
        { code: 'MH', name: '马绍尔群岛', nameEn: 'Marshall Islands', flag: '🇲🇭', continent: 'Oceania' },
        { code: 'MR', name: '毛里塔尼亚', nameEn: 'Mauritania', flag: '🇲🇷', continent: 'Africa' },
        { code: 'MU', name: '毛里求斯', nameEn: 'Mauritius', flag: '🇲🇺', continent: 'Africa' },
        { code: 'MX', name: '墨西哥', nameEn: 'Mexico', flag: '🇲🇽', continent: 'North America' },
        { code: 'FM', name: '密克罗尼西亚', nameEn: 'Micronesia', flag: '🇫🇲', continent: 'Oceania' },
        { code: 'MD', name: '摩尔多瓦', nameEn: 'Moldova', flag: '🇲🇩', continent: 'Europe' },
        { code: 'MC', name: '摩纳哥', nameEn: 'Monaco', flag: '🇲🇨', continent: 'Europe' },
        { code: 'MN', name: '蒙古', nameEn: 'Mongolia', flag: '🇲🇳', continent: 'Asia' },
        { code: 'ME', name: '黑山', nameEn: 'Montenegro', flag: '🇲🇪', continent: 'Europe' },
        { code: 'MA', name: '摩洛哥', nameEn: 'Morocco', flag: '🇲🇦', continent: 'Africa' },
        { code: 'MZ', name: '莫桑比克', nameEn: 'Mozambique', flag: '🇲🇿', continent: 'Africa' },
        { code: 'MM', name: '缅甸', nameEn: 'Myanmar', flag: '🇲🇲', continent: 'Asia' },
        { code: 'NA', name: '纳米比亚', nameEn: 'Namibia', flag: '🇳🇦', continent: 'Africa' },
        { code: 'NR', name: '瑙鲁', nameEn: 'Nauru', flag: '🇳🇷', continent: 'Oceania' },
        { code: 'NP', name: '尼泊尔', nameEn: 'Nepal', flag: '🇳🇵', continent: 'Asia' },
        { code: 'NL', name: '荷兰', nameEn: 'Netherlands', flag: '🇳🇱', continent: 'Europe' },
        { code: 'NZ', name: '新西兰', nameEn: 'New Zealand', flag: '🇳🇿', continent: 'Oceania' },
        { code: 'NI', name: '尼加拉瓜', nameEn: 'Nicaragua', flag: '🇳🇮', continent: 'North America' },
        { code: 'NE', name: '尼日尔', nameEn: 'Niger', flag: '🇳🇪', continent: 'Africa' },
        { code: 'NG', name: '尼日利亚', nameEn: 'Nigeria', flag: '🇳🇬', continent: 'Africa' },
        { code: 'NO', name: '挪威', nameEn: 'Norway', flag: '🇳🇴', continent: 'Europe' },
        { code: 'OM', name: '阿曼', nameEn: 'Oman', flag: '🇴🇲', continent: 'Asia' },
        { code: 'PK', name: '巴基斯坦', nameEn: 'Pakistan', flag: '🇵🇰', continent: 'Asia' },
        { code: 'PW', name: '帕劳', nameEn: 'Palau', flag: '🇵🇼', continent: 'Oceania' },
        { code: 'PS', name: '巴勒斯坦', nameEn: 'Palestine', flag: '🇵🇸', continent: 'Asia' },
        { code: 'PA', name: '巴拿马', nameEn: 'Panama', flag: '🇵🇦', continent: 'North America' },
        { code: 'PG', name: '巴布亚新几内亚', nameEn: 'Papua New Guinea', flag: '🇵🇬', continent: 'Oceania' },
        { code: 'PY', name: '巴拉圭', nameEn: 'Paraguay', flag: '🇵🇾', continent: 'South America' },
        { code: 'PE', name: '秘鲁', nameEn: 'Peru', flag: '🇵🇪', continent: 'South America' },
        { code: 'PH', name: '菲律宾', nameEn: 'Philippines', flag: '🇵🇭', continent: 'Asia' },
        { code: 'PL', name: '波兰', nameEn: 'Poland', flag: '🇵🇱', continent: 'Europe' },
        { code: 'PT', name: '葡萄牙', nameEn: 'Portugal', flag: '🇵🇹', continent: 'Europe' },
        { code: 'QA', name: '卡塔尔', nameEn: 'Qatar', flag: '🇶🇦', continent: 'Asia' },
        { code: 'CG', name: '刚果(布)', nameEn: 'Republic of the Congo', flag: '🇨🇬', continent: 'Africa' },
        { code: 'RO', name: '罗马尼亚', nameEn: 'Romania', flag: '🇷🇴', continent: 'Europe' },
        { code: 'RU', name: '俄罗斯', nameEn: 'Russia', flag: '🇷🇺', continent: 'Europe' },
        { code: 'RW', name: '卢旺达', nameEn: 'Rwanda', flag: '🇷🇼', continent: 'Africa' },
        { code: 'KN', name: '圣基茨和尼维斯', nameEn: 'Saint Kitts and Nevis', flag: '🇰🇳', continent: 'North America' },
        { code: 'LC', name: '圣卢西亚', nameEn: 'Saint Lucia', flag: '🇱🇨', continent: 'North America' },
        { code: 'VC', name: '圣文森特和格林纳丁斯', nameEn: 'Saint Vincent and the Grenadines', flag: '🇻🇨', continent: 'North America' },
        { code: 'WS', name: '萨摩亚', nameEn: 'Samoa', flag: '🇼🇸', continent: 'Oceania' },
        { code: 'SM', name: '圣马力诺', nameEn: 'San Marino', flag: '🇸🇲', continent: 'Europe' },
        { code: 'ST', name: '圣多美和普林西比', nameEn: 'São Tomé and Príncipe', flag: '🇸🇹', continent: 'Africa' },
        { code: 'SA', name: '沙特阿拉伯', nameEn: 'Saudi Arabia', flag: '🇸🇦', continent: 'Asia' },
        { code: 'SN', name: '塞内加尔', nameEn: 'Senegal', flag: '🇸🇳', continent: 'Africa' },
        { code: 'RS', name: '塞尔维亚', nameEn: 'Serbia', flag: '🇷🇸', continent: 'Europe' },
        { code: 'SC', name: '塞舌尔', nameEn: 'Seychelles', flag: '🇸🇨', continent: 'Africa' },
        { code: 'SL', name: '塞拉利昂', nameEn: 'Sierra Leone', flag: '🇸🇱', continent: 'Africa' },
        { code: 'SG', name: '新加坡', nameEn: 'Singapore', flag: '🇸🇬', continent: 'Asia' },
        { code: 'SK', name: '斯洛伐克', nameEn: 'Slovakia', flag: '🇸🇰', continent: 'Europe' },
        { code: 'SI', name: '斯洛文尼亚', nameEn: 'Slovenia', flag: '🇸🇮', continent: 'Europe' },
        { code: 'SB', name: '所罗门群岛', nameEn: 'Solomon Islands', flag: '🇸🇧', continent: 'Oceania' },
        { code: 'SO', name: '索马里', nameEn: 'Somalia', flag: '🇸🇴', continent: 'Africa' },
        { code: 'ZA', name: '南非', nameEn: 'South Africa', flag: '🇿🇦', continent: 'Africa' },
        { code: 'SS', name: '南苏丹', nameEn: 'South Sudan', flag: '🇸🇸', continent: 'Africa' },
        { code: 'LK', name: '斯里兰卡', nameEn: 'Sri Lanka', flag: '🇱🇰', continent: 'Asia' },
        { code: 'SD', name: '苏丹', nameEn: 'Sudan', flag: '🇸🇩', continent: 'Africa' },
        { code: 'SR', name: '苏里南', nameEn: 'Suriname', flag: '🇸🇷', continent: 'South America' },
        { code: 'SE', name: '瑞典', nameEn: 'Sweden', flag: '🇸🇪', continent: 'Europe' },
        { code: 'CH', name: '瑞士', nameEn: 'Switzerland', flag: '🇨🇭', continent: 'Europe' },
        { code: 'SY', name: '叙利亚', nameEn: 'Syria', flag: '🇸🇾', continent: 'Asia' },
        { code: 'TW', name: '中国台湾', nameEn: 'Taiwan,China', flag: '🇹🇼', continent: 'Asia' },
        { code: 'TJ', name: '塔吉克斯坦', nameEn: 'Tajikistan', flag: '🇹🇯', continent: 'Asia' },
        { code: 'TZ', name: '坦桑尼亚', nameEn: 'Tanzania', flag: '🇹🇿', continent: 'Africa' },
        { code: 'TH', name: '泰国', nameEn: 'Thailand', flag: '🇹🇭', continent: 'Asia' },
        { code: 'TL', name: '东帝汶', nameEn: 'Timor-Leste', flag: '🇹🇱', continent: 'Asia' },
        { code: 'TG', name: '多哥', nameEn: 'Togo', flag: '🇹🇬', continent: 'Africa' },
        { code: 'TO', name: '汤加', nameEn: 'Tonga', flag: '🇹🇴', continent: 'Oceania' },
        { code: 'TT', name: '特立尼达和多巴哥', nameEn: 'Trinidad and Tobago', flag: '🇹🇹', continent: 'North America' },
        { code: 'TN', name: '突尼斯', nameEn: 'Tunisia', flag: '🇹🇳', continent: 'Africa' },
        { code: 'TR', name: '土耳其', nameEn: 'Turkey', flag: '🇹🇷', continent: 'Asia' },
        { code: 'TM', name: '土库曼斯坦', nameEn: 'Turkmenistan', flag: '🇹🇲', continent: 'Asia' },
        { code: 'TV', name: '图瓦卢', nameEn: 'Tuvalu', flag: '🇹🇻', continent: 'Oceania' },
        { code: 'UG', name: '乌干达', nameEn: 'Uganda', flag: '🇺🇬', continent: 'Africa' },
        { code: 'UA', name: '乌克兰', nameEn: 'Ukraine', flag: '🇺🇦', continent: 'Europe' },
        { code: 'AE', name: '阿联酋', nameEn: 'United Arab Emirates', flag: '🇦🇪', continent: 'Asia' },
        { code: 'UY', name: '乌拉圭', nameEn: 'Uruguay', flag: '🇺🇾', continent: 'South America' },
        { code: 'UZ', name: '乌兹别克斯坦', nameEn: 'Uzbekistan', flag: '🇺🇿', continent: 'Asia' },
        { code: 'VU', name: '瓦努阿图', nameEn: 'Vanuatu', flag: '🇻🇺', continent: 'Oceania' },
        { code: 'VA', name: '梵蒂冈', nameEn: 'Vatican City', flag: '🇻🇦', continent: 'Europe' },
        { code: 'VE', name: '委内瑞拉', nameEn: 'Venezuela', flag: '🇻🇪', continent: 'South America' },
        { code: 'VN', name: '越南', nameEn: 'Vietnam', flag: '🇻🇳', continent: 'Asia' },
        { code: 'YE', name: '也门', nameEn: 'Yemen', flag: '🇾🇪', continent: 'Asia' },
        { code: 'ZM', name: '赞比亚', nameEn: 'Zambia', flag: '🇿🇲', continent: 'Africa' },
        { code: 'ZW', name: '津巴布韦', nameEn: 'Zimbabwe', flag: '🇿🇼', continent: 'Africa' }
    ];

    if (typeof module !== 'undefined' && module.exports) {
        module.exports = global.COUNTRIES_DATA;
    }
})(typeof window !== 'undefined' ? window : this);
